# Generated by Django 3.1.5 on 2021-01-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vote_total',
            new_name='votes',
        ),
    ]
